"""NLCP V2 Token Decoder Module.

DESIGN SOURCE:
    Reference: docs/concept-pyramid-V2.md
    - Section 2.2.4: Token Decoder
    - Section 1.2.2: DLCM Cross-Attention Mechanism
    - Section 1.5: Causal Cross-Attention Inheritance

PURPOSE:
    Generate tokens autoregressively by attending to final-level concepts.
    Uses causal cross-attention where tokens (as Query) attend to
    concepts (as Key/Value).

INHERITANCE FROM DLCM:
    NLCP inherits "因果交叉注意力" (causal cross-attention) from DLCM:
    - Query: Token embeddings (for autoregressive generation)
    - Key/Value: Final level concepts H_K
    - Causal mask ensures tokens only attend to previous token positions

    Why causal on tokens but not on concepts?
    - Tokens are generated autoregressively (x_t depends on x_{<t})
    - Concepts are already complete (H_K is fully generated by Concept Transformer)
    - So we apply causal mask on token dimension only

ARCHITECTURE:
    Token Embedding → [Norm → Causal Cross-Attn(H_K) → Residual]
                    → [Norm → FFN(SwiGLU) → Residual]
                    → LM Head → Logits

DIMENSION FLOW:
    Input:
        - concepts: [B, L_K, D] (H_K from Concept Transformer)
        - input_ids: [B, T] (token IDs)

    Process:
        1. Embed: [B, T] → [B, T, D]
        2. Cross-Attention: tokens(Q) attend to concepts(KV)
        3. FFN: SwiGLU activation
        4. Project: [B, T, D] → [B, T, V] (vocabulary)

    Output: [B, T, V] logits for next token prediction
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

from nlcpV2.config import NLCPV2Config
from nlcpV2.utils import create_causal_mask


class TokenDecoder(nn.Module):
    """Token decoder with causal cross-attention to concepts.

    DESIGN SOURCE: concept-pyramid-V2.md Section 1.5

    ARCHITECTURE:
        Implements DLCM's cross-attention mechanism where tokens attend to concepts:
        - Query: Token embeddings (autoregressive positions)
        - Key/Value: Final level concepts H_K (complete representation)

        This ensures concepts are used to generate tokens autoregressively,
        with gradient flow forcing concepts to contain necessary information
        for token prediction.

    CROSS-ATTENTION VS SELF-ATTENTION:
        Self-attention: Q, K, V all come from same source
        Cross-attention: Q from one source, K/V from another

        Here:
        - Q comes from token embeddings (what we're generating)
        - K/V come from concepts (what we're conditioning on)

    CAUSAL MASK APPLICATION:
        Causal mask is applied to token dimension (Query).
        Each token position can only attend to previous token positions.
        Concepts (K/V) are not masked - they're fully available.

    DIMENSION LEGEND:
        B: Batch size
        T: Token sequence length (for generation)
        L_K: Concept count at final level (K-1)
        D: Hidden dimension
        V: Vocabulary size

    Attributes:
        config: NLCPV2Config instance
        token_embedding: Token embedding [V, D]
        num_heads: Number of attention heads H
        head_dim: Per-head dimension d_head = D / H
        w_q: Query projection [D, D]
        w_k: Key projection [D, D]
        w_v: Value projection [D, D]
        w_o: Output projection [D, D]
        w_gate: FFN gate projection [D, 4D]
        w_up: FFN up projection [D, 4D]
        w_down: FFN down projection [4D, D]
        norm1: Layer norm before cross-attention
        norm2: Layer norm before FFN
        dropout: Dropout layer
        lm_head: Linear projection to vocabulary [D, V]
        muP_scale: muP scaling factor for output logits
    """

    def __init__(self, config: NLCPV2Config):
        """Initialize token decoder.

        INITIALIZATION:
            Creates all components for token generation:
            1. Token embedding layer
            2. Cross-attention projections (Q, K, V, O)
            3. FFN projections (gate, up, down)
            4. Layer norms and dropout
            5. LM head for vocabulary projection

        Args:
            config: NLCPV2Config with vocab_size, hidden_dim, num_heads
        """
        super().__init__()
        self.config = config

        self.token_embedding = nn.Embedding(config.vocab_size, config.hidden_dim)

        self.num_heads = config.num_heads
        self.head_dim = config.head_dim

        self.w_q = nn.Linear(config.hidden_dim, config.hidden_dim)
        self.w_k = nn.Linear(config.hidden_dim, config.hidden_dim)
        self.w_v = nn.Linear(config.hidden_dim, config.hidden_dim)
        self.w_o = nn.Linear(config.hidden_dim, config.hidden_dim)

        intermediate_dim = 4 * config.hidden_dim
        self.w_gate = nn.Linear(config.hidden_dim, intermediate_dim)
        self.w_up = nn.Linear(config.hidden_dim, intermediate_dim)
        self.w_down = nn.Linear(intermediate_dim, config.hidden_dim)

        self.norm1 = nn.LayerNorm(config.hidden_dim, eps=config.rms_norm_eps)
        self.norm2 = nn.LayerNorm(config.hidden_dim, eps=config.rms_norm_eps)

        self.dropout = nn.Dropout(config.dropout)

        self.lm_head = nn.Linear(
            config.hidden_dim,
            config.vocab_size,
            bias=False,
        )

        self.muP_scale = config.muP_scale

    def forward(
        self,
        concepts: torch.Tensor,
        input_ids: torch.Tensor,
    ) -> torch.Tensor:
        """Generate tokens via cross-attention to concepts.

        DESIGN SOURCE: concept-pyramid-V2.md Section 1.2.2 and 1.5

        ALGORITHM:
            1. Embed input tokens: [B, T] → [B, T, D]
            2. Apply causal cross-attention to concepts
            3. Apply FFN with residual
            4. Project to vocabulary: [B, T, D] → [B, T, V]
            5. Scale logits by muP factor

        DIMENSION FLOW:
            Input:
                concepts: [B, L_K, D] (H_K from Concept Transformer)
                input_ids: [B, T] (token IDs, e.g., CoT tokens during training)

            Step 1 - Embedding:
                x = Embed(input_ids): [B, T, D]

            Step 2 - Cross-Attention:
                causal_mask: [T, T]
                x = CrossAttnBlock(x, concepts, mask): [B, T, D]

            Step 3 - FFN:
                x = FFNBlock(x): [B, T, D]

            Step 4 - Output:
                logits = LMHead(x): [B, T, V]
                logits = logits / muP_scale: [B, T, V]

            Output: [B, T, V] logits for next token prediction

        Args:
            concepts: [B, L_K, D] Final level concepts H_K as Key/Value
                L_K = config.level_lengths[-1]
                These are the finest-grained concepts from Concept Transformer
            input_ids: [B, T] Input token IDs
                During training: Ground-truth CoT tokens (teacher forcing)
                During inference: Previously generated tokens

        Returns:
            [B, T, V] Vocabulary logits for next token prediction
                V = config.vocab_size
                logits[b, t, v] = logit for token v at position t
        """
        batch_size, seq_len = input_ids.shape
        device = input_ids.device

        x = self.token_embedding(input_ids)

        causal_mask = create_causal_mask(seq_len, device)

        x = self._cross_attention_block(x, concepts, causal_mask)

        x = self._ffn_block(x)

        logits = self.lm_head(x)
        logits = logits / self.muP_scale

        return logits

    def _cross_attention_block(
        self,
        x: torch.Tensor,
        concepts: torch.Tensor,
        causal_mask: torch.Tensor,
    ) -> torch.Tensor:
        """Cross-attention block: tokens (Q) attend to concepts (KV).

        MATHEMATICAL FORMULATION:
            Given token embeddings X ∈ R^{T×D} and concepts C ∈ R^{L_K×D}:

            1. Normalize: X_norm = Norm(X)

            2. Linear projections:
               Q = X_norm @ W_q^T    [B, T, D] (from tokens)
               K = C @ W_k^T         [B, L_K, D] (from concepts)
               V = C @ W_v^T         [B, L_K, D] (from concepts)

            3. Reshape for multi-head:
               Q = [B, H, T, d_head]
               K = [B, H, L_K, d_head]
               V = [B, H, L_K, d_head]

            4. Attention scores:
               scores = Q @ K^T / sqrt(d_head)    [B, H, T, L_K]

            5. Apply causal mask (on token dimension T):
               scores[i, j] = -inf if j > i (future tokens masked)
               Note: Concepts dimension L_K is NOT masked

            6. Softmax and weighted sum:
               attn = softmax(scores)             [B, H, T, L_K]
               output = attn @ V                  [B, H, T, d_head]

            7. Reshape and project:
               output = [B, T, D]
               output = output @ W_o^T            [B, T, D]

            8. Residual: X + Dropout(output)

        DIMENSION FLOW:
            Input x: [B, T, D] (token embeddings)
            Input concepts: [B, L_K, D] (H_K)
                ↓
            Normalize x: [B, T, D]
                ↓
            Q projection: [B, T, D]
            K projection: [B, L_K, D]
            V projection: [B, L_K, D]
                ↓
            Reshape for multi-head: [B, H, T, d_head], [B, H, L_K, d_head]
                ↓
            Attention scores: [B, H, T, L_K]
                ↓
            Apply causal mask on T dimension
                ↓
            Softmax + weighted sum: [B, H, T, d_head]
                ↓
            Reshape: [B, T, D]
                ↓
            Output projection: [B, T, D]
                ↓
            Residual: [B, T, D]

        Args:
            x: [B, T, D] Token embeddings as Query
            concepts: [B, L_K, D] Concepts as Key/Value
            causal_mask: [T, T] Causal mask for autoregressive generation
                Applied to token dimension (Query)

        Returns:
            [B, T, D] Output after cross-attention with residual
        """
        normed = self.norm1(x)

        Q = self.w_q(normed)
        K = self.w_k(concepts)
        V = self.w_v(concepts)

        batch_size, seq_len, _ = Q.shape
        kv_len = K.size(1)

        Q = Q.view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        K = K.view(batch_size, kv_len, self.num_heads, self.head_dim).transpose(1, 2)
        V = V.view(batch_size, kv_len, self.num_heads, self.head_dim).transpose(1, 2)

        scores = torch.matmul(Q, K.transpose(-2, -1)) / (self.head_dim**0.5)

        attn_weights = F.softmax(scores, dim=-1)
        attn_weights = self.dropout(attn_weights)

        output = torch.matmul(attn_weights, V)
        output = output.transpose(1, 2).contiguous()
        output = output.view(batch_size, seq_len, self.config.hidden_dim)

        output = self.w_o(output)

        x = x + self.dropout(output)

        return x

    def _ffn_block(self, x: torch.Tensor) -> torch.Tensor:
        """Feed-forward network block with SwiGLU.

        MATHEMATICAL FORMULATION:
            1. Normalize: X_norm = Norm(X)
            2. SwiGLU:
               gate = SiLU(X_norm @ W_gate^T)    [B, T, 4D]
               up = X_norm @ W_up^T              [B, T, 4D]
               hidden = gate * up                [B, T, 4D]
            3. Down project: output = hidden @ W_down^T  [B, T, D]
            4. Residual: X + Dropout(output)

        DIMENSION FLOW:
            Input x: [B, T, D]
                ↓
            Normalize: [B, T, D]
                ↓
            Gate projection + SiLU: [B, T, 4D]
            Up projection: [B, T, 4D]
                ↓
            Element-wise multiply: [B, T, 4D]
                ↓
            Dropout
                ↓
            Down projection: [B, T, D]
                ↓
            Residual: [B, T, D]

        Args:
            x: [B, T, D] Input tensor

        Returns:
            [B, T, D] Output tensor
        """
        normed = self.norm2(x)

        gate = F.silu(self.w_gate(normed))
        up = self.w_up(normed)
        hidden = gate * up
        hidden = self.dropout(hidden)
        output = self.w_down(hidden)

        x = x + output

        return x

    def generate(
        self,
        concepts: torch.Tensor,
        max_new_tokens: int,
        temperature: float = 1.0,
        top_k: int = 0,
        top_p: float = 1.0,
    ) -> torch.Tensor:
        """Autoregressive generation from concepts.

        GENERATION ALGORITHM:
            1. Initialize with empty sequence
            2. For each position t = 1 to max_new_tokens:
                a. Forward pass with current sequence
                b. Get logits for last position
                c. Apply temperature scaling
                d. Apply top-k and/or top-p filtering
                e. Sample next token from distribution
                f. Append to sequence
            3. Return generated sequence

        SAMPLING PARAMETERS:
            temperature: Controls randomness
                - T → 0: Greedy decoding (deterministic)
                - T = 1: Standard sampling
                - T > 1: More random
            top_k: Only consider top k tokens
                - 0: Disable (consider all)
                - k > 0: Only sample from top k
            top_p: Nucleus sampling
                - 1.0: Disable (consider all)
                - p < 1.0: Sample from smallest set with cumulative prob >= p

        DIMENSION FLOW:
            Input concepts: [B, L_K, D]
                ↓
            Initialize generated: [B, 0]
                ↓
            For t in range(max_new_tokens):
                input_ids = generated (or zeros for first step)
                logits = forward(concepts, input_ids): [B, t, V]
                next_logits = logits[:, -1, :]: [B, V]
                next_logits = next_logits / temperature: [B, V]
                Apply top-k/top-p filtering
                probs = softmax(next_logits): [B, V]
                next_token = sample(probs): [B, 1]
                generated = cat([generated, next_token]): [B, t+1]
                ↓
            Output: [B, max_new_tokens]

        Args:
            concepts: [B, L_K, D] Final level concepts H_K
                Used as Key/Value for all generation steps
            max_new_tokens: Maximum number of tokens to generate
            temperature: Sampling temperature (default: 1.0)
            top_k: Top-k sampling parameter (default: 0, disabled)
            top_p: Top-p (nucleus) sampling parameter (default: 1.0, disabled)

        Returns:
            [B, max_new_tokens] Generated token IDs
        """
        batch_size = concepts.size(0)
        device = concepts.device

        generated = torch.zeros(
            (batch_size, 0),
            dtype=torch.long,
            device=device,
        )

        for _ in range(max_new_tokens):
            if generated.size(1) == 0:
                input_ids = torch.zeros(
                    (batch_size, 1), dtype=torch.long, device=device
                )
            else:
                input_ids = generated

            logits = self.forward(concepts, input_ids)

            next_logits = logits[:, -1, :] / temperature

            if top_k > 0:
                indices_to_remove = (
                    next_logits < torch.topk(next_logits, top_k)[0][..., -1, None]
                )
                next_logits[indices_to_remove] = float("-inf")

            if top_p < 1.0:
                sorted_logits, sorted_indices = torch.sort(next_logits, descending=True)
                cumulative_probs = torch.cumsum(
                    torch.softmax(sorted_logits, dim=-1), dim=-1
                )
                sorted_indices_to_remove = cumulative_probs > top_p
                sorted_indices_to_remove[..., 1:] = sorted_indices_to_remove[
                    ..., :-1
                ].clone()
                sorted_indices_to_remove[..., 0] = 0
                indices_to_remove = sorted_indices_to_remove.scatter(
                    1, sorted_indices, sorted_indices_to_remove
                )
                next_logits[indices_to_remove] = float("-inf")

            probs = torch.softmax(next_logits, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)

            generated = torch.cat([generated, next_token], dim=-1)

        return generated
